name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - test-deploy-workflow
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}

      - name: Get version from package.json
        id: vars
        run: echo "VERSION=$(node -p -e \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/loopa-api:${{env.VERSION}}
            ${{ secrets.DOCKER_USERNAME}}/loopa-api:latest
